### ISSUE TITLE
the particles extraction can not be handled in binary format

### ISSUE THREAD

**Issue by ZmengXu** [blueCFD/lagrangianExtraFunctionObjects#5]
Hi, wyldckat

Thanks for your code, it helps me to read particles using paraview.
In most of my cases, OpenFOAM data is written as a binary format. However, the current utility only writes the ASCII position, thus I have ASCII position files and binary format for other fields, this makes paraview confused and report error.

Best Regards,
Zmeng

**Comment by wyldckat** [comment]
Closed by merge request #4. @ZmengXu Many thanks once again!
